const router = require('express').Router();
const userController = require('../controllers/user_controller');
const auth = require('../middleware/auth');
router.post('/register', userController.register);
router.post('/activation', userController.activateEmail);
router.post('/login', userController.login);
router.post('/refresh_token', userController.getAccessToken);
router.post('/forgot', userController.forgotPassword);
router.post('/reset',auth, userController.resetPassword);
module.exports = router;
